#!/usr/bin/env python
#
#
import dbus
bus = dbus.SessionBus()
skype = bus.get_object('com.Skype.API', '/com/Skype')
skype.Invoke('NAME linux-hotkeys')
skype.Invoke('PROTOCOL 5')
skype.Invoke('SET WINDOWSTATE NORMAL')

